apiVersion: v1
kind: ServiceAccount
metadata: {name: cb4ba-deployment-tool-sa, namespace: cp4ba-starter}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: 'system:openshift:scc:privileged', namespace: cp4ba-starter}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: 'system:openshift:scc:privileged'}
subjects:
- {kind: ServiceAccount, name: cb4ba-deployment-tool-sa, namespace: cp4ba-starter}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: cb4ba-deployment-tool-cluster-admin}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: cluster-admin}
subjects:
- {kind: ServiceAccount, name: cb4ba-deployment-tool-sa, namespace: cp4ba-starter}
