apiVersion: v1
kind: ConfigMap
metadata:
  name: cp4accelerator-cm
data:
  connection.properties: |
    apiref=${url-10}
    namespace=${project}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp4accelerator
spec:
  selector:
    matchLabels:
      app: cp4accelerator-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cp4accelerator-app
    spec:
      containers:
        - name: cp4accelerator
          image: docker.io/malekibm/cp4baacceleratoramd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 500m
          volumeMounts:
            - name: connection-cm
              mountPath: "/home/cm"
            - name: secret-volume
              mountPath: "/home/secret"
      volumes:
        - name: connection-cm
          configMap:
            name: cp4accelerator-cm
        - name: secret-volume
          secret:
            secretName: ${secret-robot}
---
kind: Service
apiVersion: v1
metadata:
  name: cp4accelerator-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cp4accelerator-app