apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpaccelerator-sa
  namespace: cp4ba-starter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp4accelerator-pvc
  namespace: cp4ba-starter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp4accelerator
  namespace: cp4ba-starter
spec:
  selector:
    matchLabels:
      app: cp4accelerator-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cp4accelerator-app
    spec:
      serviceAccountName: cpaccelerator-sa
      containers:
        - name: cp4accelerator
          image: docker.io/malekibm/cp4baacceleratoramd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 500m
          volumeMounts:
            - name: connection-cm
              mountPath: "/home/cm"
            - mountPath: /var/cp4accelerator
              name: cp4accelerator-pvc
      volumes:
        - name: connection-cm
          configMap:
            name: cp4accelerator-cm
        - name: cp4accelerator-pvc
          persistentVolumeClaim:
            claimName: cp4accelerator-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: cp4accelerator-service
  namespace: cp4ba-starter
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cp4accelerator-app