kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: robot-binding
subjects:
  - kind: ServiceAccount
    name: robot
    namespace: cp4ba-starter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: robot-mj-role
