kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: robot-mj-role
rules:
  - verbs:
      - watch
      - get
      - list
      - create
      - delete
      - update
      - patch
      - use
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
      - namespaces
  - verbs:
      - create
      - list
      - delete
      - update
      - patch
      - get
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - get
      - create
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
  - verbs:
      - update
    apiGroups:
      - apps
    resources:
      - deployments/finalizers
    resourceNames:
      - ibm-cp4a-operator
  - verbs:
      - get
      - list
      - update
      - patch
      - delete
      - create
      - watch
    apiGroups:
      - icp4a.ibm.com
    resources:
      - '*'
  - verbs:
      - get
      - list
      - update
      - patch
      - delete
      - create
      - watch
    apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
  - verbs:
      - get
      - list
      - update
      - patch
      - delete
      - create
      - watch
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods/exec
      - pods/log
  - verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
      - watch
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
  - verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
  - verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
  - verbs:
      - create
      - list
      - delete
      - update
      - patch
      - get
      - wait
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
      - deployments
  - verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
      - watch
    apiGroups:
      - ''
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - create
      - list
      - delete
      - update
      - patch
      - watch
    apiGroups:
      - ''
      - route.openshift.io
    resources:
      - routes/custom-host
  - verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
    apiGroups:
      - extensions
    resources:
      - ingresses
      - jobs
      - deployments
      - networkpolicies
      - replicasets
  - verbs:
      - create
      - watch
      - list
      - get
      - delete
      - update
      - patch
    apiGroups:
      - core.automation.ibm.com
    resources:
      - cartridges
      - automationuiconfigs
  - verbs:
      - create
      - list
      - get
      - update
      - patch
      - watch
      - delete
    apiGroups:
      - base.automation.ibm.com
    resources:
      - cartridgerequirements
      - automationbases
  - verbs:
      - create
      - get
      - delete
      - list
      - patch
      - watch
    apiGroups:
      - eventprocessing.automation.ibm.com
    resources:
      - eventprocessors
  - verbs:
      - create
      - get
      - list
      - delete
      - patch
      - update
      - watch
    apiGroups:
      - insightsengine.automation.ibm.com
    resources:
      - insightsengines
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - certmanager.k8s.io
    resources:
      - issuers
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
  - verbs:
      - create
      - delete
      - get
      - list
      - watch
      - patch
    apiGroups:
      - oidc.security.ibm.com
    resources:
      - clients
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - zen.cpd.ibm.com
    resources:
      - zenservices
      - zenextensions
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ibmevents.ibm.com
    resources:
      - kafkas
      - kafkausers
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - elastic.automation.ibm.com
    resources:
      - elasticsearches
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - icp4a.ibm.com
    resources:
      - federatedsystems

