title=Account Closure Process Mining
id=AccountClosure
description=Process Mining for Account Closure in the banking industry. This demo shows how to use process mining to analyze the account closure process and identify bottlenecks and inefficiencies.
supportTeam=Malek Jabri
type=processmining
configPage=false
enabled=true
logs=false
composer=false
updateAvailable=false
url=/processmining
urllabel=Process Mining