title=Life Claims Management
id=LifeClaimsManagement
description=Our Claims Management solution for Life Claims Management, powered by Watsonx AI, revolutionizes the way insurance companies handle claims. <br>
supportTeam=Ryan Slattery
type=baw,content
configPage=false
enabled=true
logs=false
composer=true
updateAvailable=false
url=/icn/navigator/?desktop=baw&feature=bpmWorkDashboard;/bai-bpc
urllabel=Workplace;BAI
autoUpdate=true